# Generated by Django 3.2.8 on 2021-11-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=50)),
                ('items', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
