# Generated by Django 3.2.9 on 2021-11-03 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_auto_20211102_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('cutomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clone.product')),
            ],
        ),
    ]
