# Generated by Django 3.2.9 on 2021-11-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0005_rename_cutomer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
